import { CloudStreamRepo, PlayerSettings, XtreamCredentials } from '../types';

export const DEFAULT_XTREAM_CREDENTIALS: XtreamCredentials = {
  server: 'http://8.rinastv.cfd:8080',
  username: 'Oguzhanla',
  password: '9912OYSY*',
};

export const DEFAULT_CLOUDSTREAM_REPOS: CloudStreamRepo[] = [
  {
    id: 'wiospor',
    name: 'WioSpor',
    url: 'https://raw.githubusercontent.com/Wiojelt/WioSpor/main/repo.json',
    icon: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    description: 'Canlı spor yayınları, beIN Sports, S Sport, maç özetleri ve canlı skor eklentileri.',
    author: 'Wiojelt',
    pluginCount: 4,
  },
  {
    id: 'turksinema',
    name: 'TurkSinema',
    url: 'https://raw.githubusercontent.com/Wiojelt/TurkSinema/main/repo.json',
    icon: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=120&auto=format&fit=crop&q=80',
    description: 'Yerli ve yabancı film arşivleri, 1080p/4K Türkçe dublaj ve altyazı desteği.',
    author: 'Wiojelt',
    pluginCount: 6,
  },
  {
    id: 'wiosinema',
    name: 'WioSinema',
    url: 'https://raw.githubusercontent.com/Wiojelt/WioSinema/builds/repo.json',
    icon: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=120&auto=format&fit=crop&q=80',
    description: 'Popüler dijital platform dizileri (Netflix, BluTV, Exxen, Gain) ve sinema filmleri.',
    author: 'Wiojelt',
    pluginCount: 8,
  },
  {
    id: 'kekik-akademi',
    name: 'Turkish Providers Repository | @KekikAkademi',
    url: 'https://raw.githubusercontent.com/keyiflerolsun/Kekik-cloudstream/master/repo.json',
    icon: 'https://raw.githubusercontent.com/keyiflerolsun/Kekik-cloudstream/master/icon.png',
    description: 'KekikAkademi topluluk kaynakları, dizi, film, anime ve canlı yayın sağlayıcıları.',
    author: 'KekikAkademi & keyiflerolsun',
    pluginCount: 12,
  },
];

export const DEFAULT_PLAYER_SETTINGS: PlayerSettings = {
  engine: 'exoplayer',
  bufferSize: 'standard', // 15 seconds
  hardwareAcceleration: true,
  autoFrameRate: 'match_50',
  autoQuality: true,
  audioDialogueBoost: false,
  audioDelayMs: 0,
  subtitleSize: 'medium',
  subtitleColor: 'yellow',
  subtitleBg: true,
  overscanMargin: 0,
  theme: 'oled-black',
};

export const BUFFER_PRESETS: Record<string, { label: string; seconds: number; description: string }> = {
  none: { label: 'Yok (0 sn)', seconds: 0, description: 'Sıfır gecikme (Canlı spor yayınları için ultra düşük gecikme)' },
  small: { label: 'Küçük (5 sn)', seconds: 5, description: 'Düşük RAM kullanan TV Box cihazları için hafif arabellek' },
  standard: { label: 'Standart (15 sn)', seconds: 15, description: 'Önerilen dengeli akış modu (Donma önleyici tampon)' },
  large: { label: 'Büyük (30 sn)', seconds: 30, description: 'Zayıf Wi-Fi veya dalgalı internet bağlantıları için derin önbellek' },
  very_large: { label: 'Çok Büyük (60 sn)', seconds: 60, description: 'Tampon garantili, kesintisiz ultra akıcı izleme' },
};

// All essential, out-of-the-box pre-installed TV player plugins & providers
export const DEFAULT_BUILTIN_PLUGINS: any[] = [
  // 1. Canlı Spor & Futbol
  {
    id: 'wiospor-master',
    repoId: 'wiospor',
    name: '0 WioSpor (Ana Spor & Canlı TV)',
    version: '4.2.0',
    author: 'Wiojelt',
    description: 'Tüm canlı TV ve spor kanalları tek eklentide. beIN Sports 1-5, S Sport, Exxen.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-selcuk',
    repoId: 'wiospor',
    name: 'SelçukSports HD & 4K',
    version: '12.0.4',
    author: 'Wiojelt',
    description: 'Süper Lig, Premier League, La Liga, Şampiyonlar Ligi kesintisiz maç yayınları.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-taraftarium',
    repoId: 'wiospor',
    name: 'Taraftarium24 Ultra CDN',
    version: '13.2.0',
    author: 'Wiojelt',
    description: 'Yedekli CDN sunucuları ile Full HD donmasız canlı futbol ve basketbol yayınları.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-inatbox',
    repoId: 'wiospor',
    name: 'İnat Box TV Pro',
    version: '14.5.0',
    author: 'Wiojelt',
    description: 'İnat Box doğrulanmış spor, ulusal, belgesel ve sinema canlı yayın kanalları.',
    types: ['sports', 'live', 'movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-jestyayin',
    repoId: 'wiospor',
    name: 'JestYayın & KralSpor',
    version: '4.1.0',
    author: 'Wiojelt',
    description: 'Canlı maçlar, spor kanalları ve alternatif canlı yayın akışları.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-netvgold',
    repoId: 'wiospor',
    name: 'NetV Gold Canlı Spor',
    version: '3.0.2',
    author: 'Wiojelt',
    description: 'NETV Gold uygulamasının doğrulanmış canlı spor kanalları.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiospor-trgoals',
    repoId: 'wiospor',
    name: 'TRGoals HD Live',
    version: '2.0.0',
    author: 'Wiojelt',
    description: 'TRGoals dinamik spor kanalları ve canlı maç akışları.',
    types: ['sports', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  // 2. Ulusal, Haber, Müzik & Çocuk
  {
    id: 'kekik-canlitv',
    repoId: 'kekik-akademi',
    name: 'Kekik Canlı TV Canavarı',
    version: '2.8.2',
    author: 'KekikAkademi',
    description: 'TRT 1, ATV, Kanal D, Show TV, Star, NOW, TV8, HaberTürk, NTV ve yerel kanallar.',
    types: ['live', 'sports'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'kekik-muzik',
    repoId: 'kekik-akademi',
    name: 'Kral Pop & PowerTürk Canlı Müzik',
    version: '2.0.0',
    author: 'KekikAkademi',
    description: 'Kral Pop, PowerTürk TV, Number1 TV, Dream Türk HD canlı müzik akışları.',
    types: ['live'],
    isInstalled: true,
    status: 'ready',
  },
  // 3. Sinema & Vizyon Filmleri
  {
    id: 'turksinema-hd',
    repoId: 'turksinema',
    name: 'TurkSinema Ultra 4K',
    version: '3.1.2',
    author: 'Wiojelt',
    description: 'Güncel yerli ve yabancı sinema filmleri, 1080p Türkçe dublaj ve altyazı motoru.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-bingebang',
    repoId: 'turksinema',
    name: 'BingeBang Film & Dizi',
    version: '2.5.0',
    author: 'Wiojelt',
    description: 'BingeBang 4K ve 1080p yüksek hızlı film ve dizi portali.',
    types: ['movie', 'tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-hdfilmcehennemi',
    repoId: 'turksinema',
    name: 'HDFilmCehennemi VIP',
    version: '4.5.0',
    author: 'Wiojelt',
    description: 'IMDb Top 250 ve en yeni vizyon filmleri çift dil (Dublaj/Altyazı) desteği.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-filmmakinesi',
    repoId: 'turksinema',
    name: 'Film Makinesi VIP',
    version: '4.0.0',
    author: 'Wiojelt',
    description: 'En yeni ve vizyondaki yabancı filmler, 1080p kesintisiz sunucu.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-filmmodu',
    repoId: 'turksinema',
    name: 'Film Modu 4K',
    version: '3.4.0',
    author: 'Wiojelt',
    description: 'Yüksek bitrate 1080p ve 4K filmler, altyazı ve dublaj seçenekleri.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-fullhdfilm',
    repoId: 'turksinema',
    name: 'FullHDFilm İzle',
    version: '4.2.0',
    author: 'Wiojelt',
    description: 'Türkiye\'nin en köklü film arşivi, yerli ve yabancı sinema kataloğu.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-classic',
    repoId: 'turksinema',
    name: 'Yeşilçam & Türk Klasikleri HD',
    version: '1.0.8',
    author: 'Wiojelt',
    description: 'Restore edilmiş 1080p Yeşilçam klasikleri, Kemal Sunal, Şener Şen arşivleri.',
    types: ['movie'],
    isInstalled: true,
    status: 'ready',
  },
  // 4. Diziler & Dijital Platformlar
  {
    id: 'wiosinema-master',
    repoId: 'wiosinema',
    name: '0 WioSinema Dizi & Platform',
    version: '3.5.0',
    author: 'Wiojelt',
    description: 'Türkçe film ve dizi sağlayıcıları tek çatı altında. Hızlı sonraki bölüm geçişi.',
    types: ['tv', 'movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiosinema-dizipal',
    repoId: 'wiosinema',
    name: 'DiziPal Güncel Platform',
    version: '5.2.0',
    author: 'Wiojelt',
    description: 'Netflix, HBO, Prime, Disney+ ve Apple TV+ dizilerinin tüm sezon ve bölümleri.',
    types: ['tv', 'movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiosinema-dizibox',
    repoId: 'wiosinema',
    name: 'DiziBox Yabancı Dizi',
    version: '4.8.0',
    author: 'Wiojelt',
    description: 'Popüler yabancı diziler, anlık bölüm güncellemeleri ve Türkçe altyazı.',
    types: ['tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiosinema-dizilla',
    repoId: 'wiosinema',
    name: 'Dizilla HD',
    version: '3.9.0',
    author: 'Wiojelt',
    description: 'Geniş dizi kataloğu, 1080p yüksek kaliteli akış ve çift dil desteği.',
    types: ['tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiosinema-dizimom',
    repoId: 'wiosinema',
    name: 'DiziMom Koleksiyonu',
    version: '2.8.0',
    author: 'Wiojelt',
    description: 'Binlerce yerli ve yabancı dizi arşivi, tüm sezonlar eksiksiz.',
    types: ['tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'kekik-dizikorea',
    repoId: 'kekik-akademi',
    name: 'DiziKorea (K-Drama & Asya)',
    version: '2.0.0',
    author: 'KekikAkademi',
    description: 'En güncel Kore dizileri, Asya dramaları ve Türkçe altyazılar.',
    types: ['tv'],
    isInstalled: true,
    status: 'ready',
  },
  // 5. Anime, Çizgi Film & Belgesel
  {
    id: 'kekik-animecix',
    repoId: 'kekik-akademi',
    name: 'AnimeciX Türkçe Anime',
    version: '3.8.0',
    author: 'KekikAkademi',
    description: 'Türkiye\'nin en büyük anime platformu, tüm popüler seriler ve filmler.',
    types: ['anime', 'movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-aniarsiv',
    repoId: 'turksinema',
    name: 'AniArşiv Anime Hub',
    version: '3.0.0',
    author: 'Wiojelt',
    description: 'Güncel ve klasik anime serileri ve anime filmleri, Türkçe altyazı.',
    types: ['anime', 'movie'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'turksinema-belgeselx',
    repoId: 'turksinema',
    name: 'BelgeselX Belgesel Portalı',
    version: '1.8.0',
    author: 'Wiojelt',
    description: 'Doğa, tarih, bilim ve teknoloji belgeselleri Türkçe dublaj arşivi.',
    types: ['movie', 'tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'wiosinema-dmax',
    repoId: 'wiosinema',
    name: 'DMAX & TLC Türkiye',
    version: '2.0.0',
    author: 'Wiojelt',
    description: 'DMAX belgeselleri, macera programları ve canlı TV yayınları.',
    types: ['tv', 'live'],
    isInstalled: true,
    status: 'ready',
  },
  // 6. Gelişmiş TV Motoru & Donanım Eklentileri
  {
    id: 'engine-exoplayer',
    repoId: 'builtin-engine',
    name: 'ExoPlayer v2.19 Turbo Motoru',
    version: '2.19.1',
    author: 'Google & NovaStream',
    description: 'Android TV yerel donanım kod çözücü (HEVC/H.265, AV1, MPEG-TS, HLS, DASH).',
    types: ['live', 'movie', 'tv', 'sports'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'engine-bufferguard',
    repoId: 'builtin-engine',
    name: 'BufferGuard Donma Önleyici',
    version: '3.1.0',
    author: 'NovaStream Core',
    description: '15 ila 60 saniyelik derin tamponlama ile dalgalı internette sıfır takılma.',
    types: ['live', 'sports'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'engine-subtitles',
    repoId: 'builtin-engine',
    name: 'OpenSubtitles TR Otomatik Altyazı',
    version: '2.4.0',
    author: 'OpenSubtitles API',
    description: 'Yabancı film ve dizilerde Türkçe altyazıları otomatik bulur ve senkronize eder.',
    types: ['movie', 'tv'],
    isInstalled: true,
    status: 'ready',
  },
  {
    id: 'engine-vocalclear',
    repoId: 'builtin-engine',
    name: 'VocalClear Ses & Diyalog Güçlendirici',
    version: '1.5.0',
    author: 'Dolby & NovaStream',
    description: 'Gece ve düşük sesli izlemelerde konuşmaları netleştiren ses dengeleyici.',
    types: ['movie', 'tv', 'live'],
    isInstalled: true,
    status: 'ready',
  },
];
